export type ThreatLabel = 'ad' | 'ap' | 'hybrid' | 'utility'
export type ClassLabel = 'fighter' | 'mage' | 'marksman' | 'tank' | 'support' | 'assassin'

export type ChampionThreatOverride = {
  threat: ThreatLabel
  classes: ClassLabel[]
}

function k(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9]/g, '')
}

const O: Record<string, ChampionThreatOverride> = {
  [k('Aatrox')]: { threat: 'ad', classes: ['fighter'] },
  [k('Ahri')]: { threat: 'ap', classes: ['mage', 'assassin'] },
  [k('Akali')]: { threat: 'ap', classes: ['assassin'] },
  [k('Akshan')]: { threat: 'ad', classes: ['marksman', 'assassin'] },
  [k('Alistar')]: { threat: 'utility', classes: ['tank', 'support'] },
  [k('Ambessa')]: { threat: 'ad', classes: ['fighter', 'assassin'] },
  [k('Amumu')]: { threat: 'ap', classes: ['tank'] },
  [k('Anivia')]: { threat: 'ap', classes: ['mage'] },
  [k('Annie')]: { threat: 'ap', classes: ['mage', 'support'] },
  [k('Aphelios')]: { threat: 'ad', classes: ['marksman'] },
  [k('Ashe')]: { threat: 'ad', classes: ['marksman', 'support'] },
  [k('Aurelion Sol')]: { threat: 'ap', classes: ['mage'] },
  [k('Aurora')]: { threat: 'ap', classes: ['mage', 'assassin'] },
  [k('Azir')]: { threat: 'ap', classes: ['mage'] },
  [k('Bard')]: { threat: 'utility', classes: ['support'] },
  [k("Bel'Veth")]: { threat: 'ad', classes: ['fighter'] },
  [k('Blitzcrank')]: { threat: 'utility', classes: ['tank', 'support'] },
  [k('Brand')]: { threat: 'ap', classes: ['mage', 'support'] },
  [k('Braum')]: { threat: 'utility', classes: ['tank', 'support'] },
  [k('Briar')]: { threat: 'ad', classes: ['fighter', 'assassin'] },
  [k('Caitlyn')]: { threat: 'ad', classes: ['marksman'] },
  [k('Camille')]: { threat: 'ad', classes: ['fighter'] },
  [k('Cassiopeia')]: { threat: 'ap', classes: ['mage'] },
  [k("Cho'Gath")]: { threat: 'ap', classes: ['tank', 'mage'] },
  [k('Corki')]: { threat: 'hybrid', classes: ['marksman', 'mage'] },
  [k('Darius')]: { threat: 'ad', classes: ['fighter'] },
  [k('Diana')]: { threat: 'ap', classes: ['fighter', 'assassin'] },
  [k('Dr Mundo')]: { threat: 'utility', classes: ['tank', 'fighter'] },
  [k('Dr. Mundo')]: { threat: 'utility', classes: ['tank', 'fighter'] },
  [k('Draven')]: { threat: 'ad', classes: ['marksman'] },
  [k('Ekko')]: { threat: 'ap', classes: ['assassin', 'fighter'] },
  [k('Elise')]: { threat: 'ap', classes: ['assassin', 'mage'] },
  [k('Evelynn')]: { threat: 'ap', classes: ['assassin'] },
  [k('Ezreal')]: { threat: 'ad', classes: ['marksman'] },
  [k('Fiddlesticks')]: { threat: 'ap', classes: ['mage'] },
  [k('Fiora')]: { threat: 'ad', classes: ['fighter'] },
  [k('Fizz')]: { threat: 'ap', classes: ['assassin'] },
  [k('Galio')]: { threat: 'ap', classes: ['tank', 'mage'] },
  [k('Gangplank')]: { threat: 'ad', classes: ['fighter'] },
  [k('Garen')]: { threat: 'ad', classes: ['fighter'] },
  [k('Gnar')]: { threat: 'ad', classes: ['fighter', 'tank'] },
  [k('Gragas')]: { threat: 'ap', classes: ['tank', 'fighter'] },
  [k('Graves')]: { threat: 'ad', classes: ['marksman', 'fighter'] },
  [k('Gwen')]: { threat: 'ap', classes: ['fighter'] },
  [k('Hecarim')]: { threat: 'ad', classes: ['fighter'] },
  [k('Heimerdinger')]: { threat: 'ap', classes: ['mage'] },
  [k('Hwei')]: { threat: 'ap', classes: ['mage'] },
  [k('Illaoi')]: { threat: 'ad', classes: ['fighter'] },
  [k('Irelia')]: { threat: 'ad', classes: ['fighter'] },
  [k('Ivern')]: { threat: 'utility', classes: ['support'] },
  [k('Janna')]: { threat: 'utility', classes: ['support'] },
  [k('Jarvan IV')]: { threat: 'ad', classes: ['fighter', 'tank'] },
  [k('Jax')]: { threat: 'ad', classes: ['fighter'] },
  [k('Jayce')]: { threat: 'ad', classes: ['fighter', 'marksman'] },
  [k('Jhin')]: { threat: 'ad', classes: ['marksman'] },
  [k('Jinx')]: { threat: 'ad', classes: ['marksman'] },
  [k("K'Sante")]: { threat: 'utility', classes: ['tank', 'fighter'] },
  [k("Kai'Sa")]: { threat: 'hybrid', classes: ['marksman'] },
  [k('Kalista')]: { threat: 'ad', classes: ['marksman'] },
  [k('Karma')]: { threat: 'ap', classes: ['support', 'mage'] },
  [k('Karthus')]: { threat: 'ap', classes: ['mage'] },
  [k('Kassadin')]: { threat: 'ap', classes: ['assassin'] },
  [k('Katarina')]: { threat: 'ap', classes: ['assassin'] },
  [k('Kayle')]: { threat: 'hybrid', classes: ['mage', 'marksman'] },
  [k('Kayn')]: { threat: 'ad', classes: ['fighter', 'assassin'] },
  [k('Kennen')]: { threat: 'ap', classes: ['mage'] },
  [k("Kha'Zix")]: { threat: 'ad', classes: ['assassin'] },
  [k('Kindred')]: { threat: 'ad', classes: ['marksman'] },
  [k('Kled')]: { threat: 'ad', classes: ['fighter'] },
  [k("Kog'Maw")]: { threat: 'hybrid', classes: ['marksman'] },
  [k('LeBlanc')]: { threat: 'ap', classes: ['mage', 'assassin'] },
  [k('Lee Sin')]: { threat: 'ad', classes: ['fighter'] },
  [k('Leona')]: { threat: 'utility', classes: ['tank', 'support'] },
  [k('Lillia')]: { threat: 'ap', classes: ['fighter', 'mage'] },
  [k('Lissandra')]: { threat: 'ap', classes: ['mage'] },
  [k('Lucian')]: { threat: 'ad', classes: ['marksman'] },
  [k('Lulu')]: { threat: 'utility', classes: ['support'] },
  [k('Lux')]: { threat: 'ap', classes: ['mage', 'support'] },
  [k('Malphite')]: { threat: 'utility', classes: ['tank', 'mage'] },
  [k('Malzahar')]: { threat: 'ap', classes: ['mage'] },
  [k('Maokai')]: { threat: 'utility', classes: ['tank', 'support'] },
  [k('Master Yi')]: { threat: 'ad', classes: ['fighter', 'assassin'] },
  [k('Mel')]: { threat: 'ap', classes: ['mage', 'support'] },
  [k('Milio')]: { threat: 'utility', classes: ['support'] },
  [k('Miss Fortune')]: { threat: 'ad', classes: ['marksman'] },
  [k('Mordekaiser')]: { threat: 'ap', classes: ['fighter'] },
  [k('Morgana')]: { threat: 'ap', classes: ['mage', 'support'] },
  [k('Naafiri')]: { threat: 'ad', classes: ['assassin', 'fighter'] },
  [k('Nami')]: { threat: 'utility', classes: ['support'] },
  [k('Nasus')]: { threat: 'ad', classes: ['fighter', 'tank'] },
  [k('Nautilus')]: { threat: 'utility', classes: ['tank', 'support'] },
  [k('Neeko')]: { threat: 'ap', classes: ['mage', 'support'] },
  [k('Nidalee')]: { threat: 'ap', classes: ['mage', 'assassin'] },
  [k('Nilah')]: { threat: 'ad', classes: ['marksman', 'fighter'] },
  [k('Nocturne')]: { threat: 'ad', classes: ['assassin', 'fighter'] },
  [k('Nunu & Willump')]: { threat: 'ap', classes: ['tank', 'mage'] },
  [k('Olaf')]: { threat: 'ad', classes: ['fighter'] },
  [k('Orianna')]: { threat: 'ap', classes: ['mage'] },
  [k('Ornn')]: { threat: 'utility', classes: ['tank'] },
  [k('Pantheon')]: { threat: 'ad', classes: ['fighter', 'assassin'] },
  [k('Poppy')]: { threat: 'utility', classes: ['tank', 'fighter'] },
  [k('Pyke')]: { threat: 'ad', classes: ['support', 'assassin'] },
  [k('Qiyana')]: { threat: 'ad', classes: ['assassin'] },
  [k('Quinn')]: { threat: 'ad', classes: ['marksman'] },
  [k('Rakan')]: { threat: 'utility', classes: ['support'] },
  [k('Rammus')]: { threat: 'utility', classes: ['tank'] },
  [k("Rek'Sai")]: { threat: 'ad', classes: ['fighter'] },
  [k('Rell')]: { threat: 'utility', classes: ['tank', 'support'] },
  [k('Renata Glasc')]: { threat: 'utility', classes: ['support'] },
  [k('Renekton')]: { threat: 'ad', classes: ['fighter'] },
  [k('Rengar')]: { threat: 'ad', classes: ['assassin', 'fighter'] },
  [k('Riven')]: { threat: 'ad', classes: ['fighter'] },
  [k('Rumble')]: { threat: 'ap', classes: ['fighter', 'mage'] },
  [k('Ryze')]: { threat: 'ap', classes: ['mage'] },
  [k('Samira')]: { threat: 'ad', classes: ['marksman', 'assassin'] },
  [k('Sejuani')]: { threat: 'utility', classes: ['tank'] },
  [k('Senna')]: { threat: 'ad', classes: ['marksman', 'support'] },
  [k('Seraphine')]: { threat: 'ap', classes: ['mage', 'support'] },
  [k('Sett')]: { threat: 'ad', classes: ['fighter', 'tank'] },
  [k('Shaco')]: { threat: 'hybrid', classes: ['assassin'] },
  [k('Shen')]: { threat: 'utility', classes: ['tank'] },
  [k('Shyvana')]: { threat: 'hybrid', classes: ['fighter', 'tank'] },
  [k('Singed')]: { threat: 'ap', classes: ['tank', 'mage'] },
  [k('Sion')]: { threat: 'utility', classes: ['tank', 'fighter'] },
  [k('Sivir')]: { threat: 'ad', classes: ['marksman'] },
  [k('Skarner')]: { threat: 'utility', classes: ['tank', 'fighter'] },
  [k('Smolder')]: { threat: 'hybrid', classes: ['marksman'] },
  [k('Sona')]: { threat: 'utility', classes: ['support'] },
  [k('Soraka')]: { threat: 'utility', classes: ['support'] },
  [k('Swain')]: { threat: 'ap', classes: ['mage', 'support'] },
  [k('Sylas')]: { threat: 'ap', classes: ['mage', 'fighter'] },
  [k('Syndra')]: { threat: 'ap', classes: ['mage'] },
  [k('Tahm Kench')]: { threat: 'utility', classes: ['tank', 'support'] },
  [k('Taliyah')]: { threat: 'ap', classes: ['mage'] },
  [k('Talon')]: { threat: 'ad', classes: ['assassin'] },
  [k('Taric')]: { threat: 'utility', classes: ['support', 'tank'] },
  [k('Teemo')]: { threat: 'ap', classes: ['marksman', 'mage'] },
  [k('Thresh')]: { threat: 'utility', classes: ['support', 'tank'] },
  [k('Tristana')]: { threat: 'ad', classes: ['marksman'] },
  [k('Trundle')]: { threat: 'ad', classes: ['fighter'] },
  [k('Tryndamere')]: { threat: 'ad', classes: ['fighter'] },
  [k('Twisted Fate')]: { threat: 'ap', classes: ['mage', 'marksman'] },
  [k('Twitch')]: { threat: 'hybrid', classes: ['marksman'] },
  [k('Udyr')]: { threat: 'hybrid', classes: ['fighter', 'tank'] },
  [k('Urgot')]: { threat: 'ad', classes: ['fighter'] },
  [k('Varus')]: { threat: 'hybrid', classes: ['marksman'] },
  [k('Vayne')]: { threat: 'ad', classes: ['marksman'] },
  [k('Veigar')]: { threat: 'ap', classes: ['mage'] },
  [k("Vel'Koz")]: { threat: 'ap', classes: ['mage', 'support'] },
  [k('Vex')]: { threat: 'ap', classes: ['mage'] },
  [k('Vi')]: { threat: 'ad', classes: ['fighter'] },
  [k('Viego')]: { threat: 'ad', classes: ['fighter', 'assassin'] },
  [k('Viktor')]: { threat: 'ap', classes: ['mage'] },
  [k('Vladimir')]: { threat: 'ap', classes: ['mage'] },
  [k('Volibear')]: { threat: 'hybrid', classes: ['fighter', 'tank'] },
  [k('Warwick')]: { threat: 'hybrid', classes: ['fighter', 'tank'] },
  [k('Wukong')]: { threat: 'ad', classes: ['fighter'] },
  [k('Xayah')]: { threat: 'ad', classes: ['marksman'] },
  [k('Xerath')]: { threat: 'ap', classes: ['mage', 'support'] },
  [k('Xin Zhao')]: { threat: 'ad', classes: ['fighter'] },
  [k('Yasuo')]: { threat: 'ad', classes: ['fighter', 'marksman'] },
  [k('Yone')]: { threat: 'ad', classes: ['fighter', 'assassin'] },
  [k('Yorick')]: { threat: 'ad', classes: ['fighter'] },
  [k('Yunara')]: { threat: 'hybrid', classes: ['marksman'] },
  [k('Yuumi')]: { threat: 'utility', classes: ['support'] },
  [k('Zaahen')]: { threat: 'ad', classes: ['fighter', 'assassin'] },
  [k('Zac')]: { threat: 'utility', classes: ['tank'] },
  [k('Zed')]: { threat: 'ad', classes: ['assassin'] },
  [k('Zeri')]: { threat: 'ad', classes: ['marksman'] },
  [k('Ziggs')]: { threat: 'ap', classes: ['mage'] },
  [k('Zilean')]: { threat: 'utility', classes: ['support', 'mage'] },
  [k('Zoe')]: { threat: 'ap', classes: ['mage'] },
  [k('Zyra')]: { threat: 'ap', classes: ['mage', 'support'] }
}

export function getChampionThreatOverride(name: string | null | undefined): ChampionThreatOverride | null {
  if (!name) {
    return null
  }
  return O[k(name)] ?? null
}

export function championThreatOverrideRows(): { key: string; threat: ThreatLabel; classes: ClassLabel[] }[] {
  return Object.entries(O).map(([key, value]) => ({ key, threat: value.threat, classes: value.classes }))
}

