function norm(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9]/g, '')
}

/** champion -> champs that hard-counter champion */
const HARD_COUNTERS_RAW: Record<string, string[]> = {
  "Aatrox": ["Irelia", "Fiora", "Kled", "Singed", "Jax"],
  "Ahri": ["Yasuo", "Sylas", "Kassadin", "Fizz", "Zed"],
  "Akali": ["Pantheon", "Galio", "Twisted Fate", "Kled", "Vex"],
  "Akshan": ["Yasuo", "Irelia", "Pantheon", "Jax", "Syndra"],
  "Alistar": ["Sylas", "Janna", "Morgana", "Braum", "Taric"],
  "Ambessa": ["Poppy", "Jax", "Malphite", "Cassiopeia", "Vayne"],
  "Amumu": ["Karthus", "Olaf", "Trundle", "Sylas", "Zac"],
  "Anivia": ["Kassadin", "Fizz", "Zed", "Katarina", "Viktor"],
  "Annie": ["Syndra", "Orianna", "Xerath", "Vel'Koz", "Zed"],
  "Aphelios": ["Braum", "Yasuo", "Nautilus", "Leona", "Blitzcrank"],
  "Ashe": ["Nautilus", "Leona", "Blitzcrank", "Pyke", "Braum"],
  "Aurelion Sol": ["Zed", "Fizz", "Kassadin", "Yone", "Qiyana"],
  "Aurora": ["Kassadin", "Yone", "Yasuo", "Zed", "Irelia"],
  "Azir": ["Xerath", "Vel'Koz", "Ziggs", "Kassadin", "Syndra"],
  "Bard": ["Morgana", "Pyke", "Blitzcrank", "Nautilus", "Thresh"],
  "Bel'Veth": ["Rammus", "Amumu", "Poppy", "Jax", "Sejuani"],
  "Blitzcrank": ["Morgana", "Leona", "Alistar", "Braum", "Taric"],
  "Brand": ["Vel'Koz", "Xerath", "Fizz", "Zed", "Ekko"],
  "Braum": ["Morgana", "Karma", "Zyra", "Lux", "Xerath"],
  "Briar": ["Rammus", "Jax", "Nocturne", "Amumu", "Shen"],
  "Caitlyn": ["Sivir", "Ashe", "Varus", "Jhin", "Tristana"],
  "Camille": ["Jax", "Fiora", "Darius", "Mordekaiser", "Renekton"],
  "Cassiopeia": ["Syndra", "Galio", "Orianna", "Xerath", "Vel'Koz"],
  "Cho'Gath": ["Fiora", "Vayne", "Kled", "Gwen", "Sett"],
  "Corki": ["Yasuo", "Draven", "Caitlyn", "Syndra", "Zed"],
  "Darius": ["Vayne", "Quinn", "Teemo", "Jayce", "Wukong"],
  "Diana": ["Galio", "Mordekaiser", "Swain", "Kassadin", "Yasuo"],
  "Dr. Mundo": ["Vayne", "Gwen", "Fiora", "Aatrox", "Kled"],
  "Draven": ["Varus", "Caitlyn", "Ashe", "Nilah", "Samira"],
  "Ekko": ["Kassadin", "Sylas", "LeBlanc", "Vex", "Pantheon"],
  "Elise": ["Rengar", "Kha'Zix", "Lee Sin", "Olaf", "Udyr"],
  "Evelynn": ["Rengar", "Rek'Sai", "Lee Sin", "Kha'Zix", "Nidalee"],
  "Ezreal": ["Vayne", "Draven", "Caitlyn", "Twitch", "Sivir"],
  "Fiddlesticks": ["Xin Zhao", "Olaf", "Lee Sin", "Jarvan IV", "Nocturne"],
  "Fiora": ["Malphite", "Pantheon", "Kennen", "Akali", "Wukong"],
  "Fizz": ["Kassadin", "Galio", "Pantheon", "Vex", "Lissandra"],
  "Galio": ["Vayne", "Lucian", "Tristana", "Fiora", "Camille"],
  "Gangplank": ["Quinn", "Lucian", "Riven", "Irelia", "Tryndamere"],
  "Garen": ["Vayne", "Teemo", "Quinn", "Camille", "Kayle"],
  "Gnar": ["Irelia", "Yasuo", "Fiora", "Wukong", "Riven"],
  "Gragas": ["Yasuo", "Sylas", "Viego", "Garen", "Darius"],
  "Graves": ["Nidalee", "Elise", "Lee Sin", "Xin Zhao", "Evelynn"],
  "Gwen": ["Fiora", "Jax", "Riven", "Tryndamere", "Renekton"],
  "Hecarim": ["Rammus", "Sejuani", "Udyr", "Olaf", "Zac"],
  "Heimerdinger": ["Syndra", "Yasuo", "Irelia", "Xerath", "Vel'Koz"],
  "Hwei": ["Fizz", "Zed", "Katarina", "Kassadin", "Yasuo"],
  "Illaoi": ["Yorick", "Mordekaiser", "Tryndamere", "Garen", "Vayne"],
  "Irelia": ["Jax", "Shen", "Fiora", "Volibear", "Sett"],
  "Ivern": ["Rengar", "Kha'Zix", "Lee Sin", "Nidalee", "Graves"],
  "Janna": ["Blitzcrank", "Sona", "Nami", "Soraka", "Senna"],
  "Jarvan IV": ["Poppy", "Xin Zhao", "Vi", "Olaf", "Sejuani"],
  "Jax": ["Malphite", "Garen", "Pantheon", "Kennen", "Singed"],
  "Jayce": ["Irelia", "Wukong", "Malphite", "Ornn", "Sion"],
  "Jhin": ["Tristana", "Draven", "Vayne", "Twitch", "Lucian"],
  "Jinx": ["Draven", "Twitch", "Tristana", "Lucian", "Miss Fortune"],
  "K'Sante": ["Fiora", "Garen", "Darius", "Camille", "Vayne"],
  "Kai'Sa": ["Caitlyn", "Draven", "Xayah", "Ashe", "Varus"],
  "Kalista": ["Ashe", "Draven", "Vayne", "Tristana", "Twitch"],
  "Karma": ["Sona", "Nami", "Soraka", "Yuumi", "Senna"],
  "Karthus": ["Ekko", "Fizz", "Zed", "Katarina", "Kassadin"],
  "Kassadin": ["Talon", "Zed", "Pantheon", "Qiyana", "Lucian"],
  "Katarina": ["Galio", "Kassadin", "Vex", "Pantheon", "Lissandra"],
  "Kayle": ["Jax", "Tryndamere", "Irelia", "Riven", "Renekton"],
  "Kayn": ["Graves", "Nidalee", "Lee Sin", "Xin Zhao", "Kindred"],
  "Kennen": ["Sylas", "Jayce", "Irelia", "Ryze", "Cassiopeia"],
  "Kha'Zix": ["Rengar", "Lee Sin", "Udyr", "Elise", "Vi"],
  "Kindred": ["Lee Sin", "Xin Zhao", "Graves", "Master Yi", "Rengar"],
  "Kled": ["Fiora", "Jax", "Shen", "Teemo", "Vayne"],
  "Kog'Maw": ["Draven", "Lucian", "Tristana", "Twitch", "Vayne"],
  "LeBlanc": ["Vex", "Galio", "Lissandra", "Malzahar", "Syndra"],
  "Lee Sin": ["Udyr", "Trundle", "Rek'Sai", "Vi", "Poppy"],
  "Leona": ["Morgana", "Janna", "Thresh", "Alistar", "Taric"],
  "Lillia": ["Rengar", "Kha'Zix", "Lee Sin", "Jarvan IV", "Vi"],
  "Lissandra": ["Sylas", "Kassadin", "Syndra", "Orianna", "Xerath"],
  "Lucian": ["Draven", "Caitlyn", "Ashe", "Vayne", "Twitch"],
  "Lulu": ["Brand", "Zyra", "Xerath", "Vel'Koz", "Sona"],
  "Lux": ["Fizz", "Yasuo", "Zed", "Katarina", "Kassadin"],
  "Malphite": ["Sylas", "Mordekaiser", "Rumble", "Vladimir", "Cho'Gath"],
  "Malzahar": ["Syndra", "Orianna", "Xerath", "Vel'Koz", "Lux"],
  "Maokai": ["Darius", "Mordekaiser", "Illaoi", "Kled", "Aatrox"],
  "Master Yi": ["Rammus", "Udyr", "Jax", "Wukong", "Shaco"],
  "Mel": ["Kassadin", "Syndra", "Zed", "Talon", "Fizz"],
  "Milio": ["Blitzcrank", "Nautilus", "Leona", "Pyke", "Thresh"],
  "Miss Fortune": ["Tristana", "Draven", "Yasuo", "Samira", "Nilah"],
  "Mordekaiser": ["Fiora", "Vayne", "Olaf", "Tryndamere", "Jax"],
  "Morgana": ["Karma", "Sona", "Nami", "Soraka", "Senna"],
  "Naafiri": ["Irelia", "Yasuo", "Pantheon", "Renekton", "Kled"],
  "Nami": ["Nautilus", "Blitzcrank", "Leona", "Pyke", "Thresh"],
  "Nasus": ["Darius", "Teemo", "Illaoi", "Garen", "Camille"],
  "Nautilus": ["Morgana", "Braum", "Taric", "Leona", "Alistar"],
  "Neeko": ["Syndra", "Vel'Koz", "Xerath", "Orianna", "Lux"],
  "Nidalee": ["Rengar", "Kha'Zix", "Lee Sin", "Elise", "Evelynn"],
  "Nilah": ["Xayah", "Caitlyn", "Ashe", "Varus", "Jhin"],
  "Nocturne": ["Udyr", "Rammus", "Olaf", "Warwick", "Trundle"],
  "Nunu & Willump": ["Trundle", "Udyr", "Master Yi", "Amumu", "Zac"],
  "Olaf": ["Kled", "Fiora", "Trundle", "Yorick", "Illaoi"],
  "Orianna": ["Syndra", "Zed", "Fizz", "Katarina", "Yasuo"],
  "Ornn": ["Fiora", "Shen", "Trundle", "Camille", "Gwen"],
  "Pantheon": ["Malphite", "Shen", "Maokai", "Sion", "Ornn"],
  "Poppy": ["Darius", "Olaf", "Garen", "Renekton", "Sett"],
  "Pyke": ["Morgana", "Leona", "Nautilus", "Alistar", "Taric"],
  "Qiyana": ["Vex", "Pantheon", "Galio", "Renekton", "Garen"],
  "Quinn": ["Malphite", "Irelia", "Pantheon", "Teemo", "Wukong"],
  "Rakan": ["Morgana", "Thresh", "Janna", "Leona", "Alistar"],
  "Rammus": ["Trundle", "Zac", "Amumu", "Sejuani", "Maokai"],
  "Rek'Sai": ["Elise", "Lee Sin", "Udyr", "Trundle", "Vi"],
  "Rell": ["Janna", "Thresh", "Morgana", "Alistar", "Poppy"],
  "Renata Glasc": ["Xerath", "Vel'Koz", "Zyra", "Brand", "Lux"],
  "Renekton": ["Illaoi", "Garen", "Quinn", "Teemo", "Vayne"],
  "Rengar": ["Lee Sin", "Udyr", "Vi", "Rek'Sai", "Warwick"],
  "Riven": ["Renekton", "Poppy", "Kennen", "Volibear", "Garen"],
  "Rumble": ["Yorick", "Darius", "Aatrox", "Kled", "Illaoi"],
  "Ryze": ["Cassiopeia", "Anivia", "Syndra", "Orianna", "Xerath"],
  "Samira": ["Senna", "Aphelios", "Nilah", "Ashe", "Jhin"],
  "Sejuani": ["Trundle", "Amumu", "Zac", "Olaf", "Rammus"],
  "Senna": ["Nautilus", "Leona", "Blitzcrank", "Pyke", "Thresh"],
  "Seraphine": ["Blitzcrank", "Pyke", "Nautilus", "Leona", "Thresh"],
  "Sett": ["Volibear", "Renekton", "Kled", "Aatrox", "Mordekaiser"],
  "Shaco": ["Rek'Sai", "Lee Sin", "Vi", "Rengar", "Udyr"],
  "Shen": ["Gangplank", "Darius", "Mordekaiser", "Aatrox", "Illaoi"],
  "Shyvana": ["Udyr", "Trundle", "Olaf", "Xin Zhao", "Lee Sin"],
  "Singed": ["Kayle", "Vayne", "Teemo", "Kennen", "Jayce"],
  "Sion": ["Darius", "Aatrox", "Kled", "Fiora", "Gwen"],
  "Sivir": ["Vayne", "Draven", "Twitch", "Tristana", "Kalista"],
  "Skarner": ["Olaf", "Morgana", "Trundle", "Udyr", "Vayne"],
  "Smolder": ["Draven", "Lucian", "Tristana", "Caitlyn", "Kalista"],
  "Sona": ["Blitzcrank", "Leona", "Nautilus", "Pyke", "Thresh"],
  "Soraka": ["Nautilus", "Pyke", "Blitzcrank", "Leona", "Thresh"],
  "Swain": ["Sylas", "Katarina", "Yone", "Yasuo", "Fizz"],
  "Sylas": ["Cassiopeia", "Vex", "Galio", "Pantheon", "Kassadin"],
  "Syndra": ["Fizz", "Ekko", "Zed", "Katarina", "Yasuo"],
  "Tahm Kench": ["Vayne", "Fiora", "Shen", "Yorick", "Illaoi"],
  "Taliyah": ["Katarina", "Zed", "Fizz", "Ekko", "Kassadin"],
  "Talon": ["Pantheon", "Diana", "Galio", "Vex", "Lissandra"],
  "Taric": ["Morgana", "Lulu", "Janna", "Nami", "Soraka"],
  "Teemo": ["Pantheon", "Ryze", "Cassiopeia", "Syndra", "Annie"],
  "Thresh": ["Morgana", "Zyra", "Brand", "Vel'Koz", "Xerath"],
  "Tristana": ["Draven", "Twitch", "Vayne", "Yasuo", "Nilah"],
  "Trundle": ["Teemo", "Kennen", "Vayne", "Quinn", "Jayce"],
  "Tryndamere": ["Malphite", "Jax", "Tahm Kench", "Shen", "Rammus"],
  "Twisted Fate": ["Fizz", "Yasuo", "Zed", "Katarina", "Ekko"],
  "Twitch": ["Draven", "Caitlyn", "Tristana", "Lucian", "Ashe"],
  "Udyr": ["Ashe", "Vayne", "Trundle", "Olaf", "Jax"],
  "Urgot": ["Rammus", "Shen", "Mordekaiser", "Aatrox", "Kled"],
  "Varus": ["Tristana", "Draven", "Lucian", "Twitch", "Vayne"],
  "Vayne": ["Draven", "Caitlyn", "Ashe", "Miss Fortune", "Jhin"],
  "Veigar": ["Katarina", "Fizz", "Zed", "Ekko", "Kassadin"],
  "Vel'Koz": ["Fizz", "Zed", "Katarina", "LeBlanc", "Yasuo"],
  "Vex": ["Syndra", "Orianna", "Xerath", "Vel'Koz", "Lux"],
  "Vi": ["Morgana", "Janna", "Vayne", "Poppy", "Trundle"],
  "Viego": ["Rammus", "Udyr", "Jax", "Wukong", "Poppy"],
  "Viktor": ["Syndra", "Ekko", "Fizz", "Zed", "Kassadin"],
  "Vladimir": ["Malzahar", "Anivia", "Cassiopeia", "Ryze", "Syndra"],
  "Volibear": ["Illaoi", "Vayne", "Teemo", "Quinn", "Kennen"],
  "Warwick": ["Olaf", "Udyr", "Trundle", "Volibear", "Jax"],
  "Wukong": ["Malphite", "Garen", "Darius", "Mordekaiser", "Illaoi"],
  "Xayah": ["Caitlyn", "Draven", "Ashe", "Varus", "Jhin"],
  "Xerath": ["Fizz", "Zed", "Katarina", "LeBlanc", "Ekko"],
  "Xin Zhao": ["Jax", "Rammus", "Udyr", "Trundle", "Olaf"],
  "Yasuo": ["Annie", "Renekton", "Pantheon", "Vex", "Lissandra"],
  "Yone": ["Pantheon", "Vex", "Renekton", "Annie", "Lissandra"],
  "Yorick": ["Irelia", "Tryndamere", "Jax", "Shen", "Volibear"],
  "Yunara": ["Nilah", "Samira", "Draven", "Lucian", "Tristana"],
  "Yuumi": ["Nautilus", "Leona", "Blitzcrank", "Pyke", "Thresh"],
  "Zaahen": ["Fiora", "Malphite", "Jax", "Kled", "Aatrox"],
  "Zac": ["Thresh", "Janna", "Vayne", "Poppy", "Trundle"],
  "Zed": ["Lissandra", "Malphite", "Garen", "Renekton", "Pantheon"],
  "Zeri": ["Draven", "Twitch", "Tristana", "Lucian", "Vayne"],
  "Ziggs": ["Yasuo", "Zed", "Fizz", "Katarina", "Ekko"],
  "Zilean": ["Syndra", "Orianna", "Xerath", "Vel'Koz", "Lux"],
  "Zoe": ["Yasuo", "Yone", "Zed", "Fizz", "Syndra"],
  "Zyra": ["Xerath", "Vel'Koz", "Brand", "Lux", "Ziggs"]
}

export const HARD_COUNTERS_BY_NAME: ReadonlyMap<string, readonly string[]> = new Map(
  Object.entries(HARD_COUNTERS_RAW).map(([champ, counters]) => [norm(champ), counters.map(norm)])
)

export function hardCounterBonusByName(allyChampionName: string, enemyChampionName: string): number {
  const ally = norm(allyChampionName)
  const enemy = norm(enemyChampionName)
  const enemyCounters = HARD_COUNTERS_BY_NAME.get(enemy)
  const allyCounters = HARD_COUNTERS_BY_NAME.get(ally)
  let bonus = 0
  if (enemyCounters?.includes(ally)) {
    bonus += 8
  }
  if (allyCounters?.includes(enemy)) {
    bonus -= 8
  }
  return bonus
}

